export default {
  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
  ACCOUNT_SET_IS_LOGGED_IN: 'ACCOUNT_SET_IS_LOGGED_IN',

  PEERPLAYS_SET_IS_CONNECTED: 'PEERPLAYS_SET_IS_CONNECTED',
  PEERPLAYS_SET_ACCOUNT: 'PEERPLAYS_SET_ACCOUNT',
  PEERPLAYS_SET_PRECISION: 'PEERPLAYS_SET_PRECISION',
  PEERPLAYS_SET_BALANCE: 'PEERPLAYS_SET_BALANCE',
  PEERPLAYS_SET_PASSWORD: 'PEERPLAYS_SET_PASSWORD',
  PEERPLAYS_SET_TRANSFERFEE: 'PEERPLAYS_SET_TRANSFERFEE',

  NFT_SELECTED_FOR_MARKETPLACE: 'NFT_SELECTED_FOR_MARKETPLACE',
  NFT_SELECTED_FOR_BIDDING: 'NFT_SELECTED_FOR_BIDDING'
};
