export default {
  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
  ACCOUNT_SET_IS_LOGGED_IN: 'ACCOUNT_SET_IS_LOGGED_IN',

  PEERPLAYS_SET_IS_CONNECTED: 'PEERPLAYS_SET_IS_CONNECTED',
  PEERPLAYS_SET_ACCOUNT: 'PEERPLAYS_SET_ACCOUNT',
  PEERPLAYS_SET_PRECISION: 'PEERPLAYS_SET_PRECISION',
  PEERPLAYS_SET_BALANCE: 'PEERPLAYS_SET_BALANCE',
  PEERPLAYS_SET_PASSWORD: 'PEERPLAYS_SET_PASSWORD',
  PEERPLAYS_SET_TRANSFERFEE: 'PEERPLAYS_SET_TRANSFERFEE'
};
